### PR TITLE
Remove all components

### PR DESCRIPTION
**Pull request by Sweattypalms**

### CODE REVIEW

**Comment by ReCore-sys** [comment]
What's it for?

**Comment by Sweattypalms** [comment]
removes components of an entity when a connection ends. to save memory perhaps? it'd be useful to save data of an entity that disconnected.

**Comment by Skullians** [comment]
of _an_ entity???
do you mean the player?

**Review by Sweattypalms — COMMENTED** [review]
I love reviewing my own code

**Pull request merged**
